### ISSUE TITLE
Здравствуйте! У меня вопрос

### ISSUE THREAD

**Issue by BlackCatDevel0per** [qPexLegendary/FormAPI#4]
Здравствуйте! У меня вопрос как добавить плагин в зависимости в pom.xml?(для использования библиотек плагина)
И подайдёт ли этот плагин для ядра PowerNukkit?

**Comment by BlackCatDevel0per** [comment]
Думаю использовать ваш плагин для своего плагина ShopUI под ядро PowerNukkit

**Comment by IWareQ** [comment]
Плагин подойдет для PowerNukkit.

Чтобы добавить его в зависимость достаточно прописать это в pom.xml и закинуть FormAPI.jar в папку libs вашего проекта:

```
<dependency>
    <groupId>ru.nukkitx</groupId>
    <artifactId>FormAPI</artifactId>
    <version>2.2-SNAPSHOT</version>
    <scope>system</scope>
    <systemPath>${basedir}/libs/FormAPI.jar</systemPath>
</dependency>
```
