### ISSUE TITLE
[question] code 

### ISSUE THREAD

**Issue by Bubbelwubbel** [qPexLegendary/FormAPI#5]
[Nukkit: https://cloudburstmc.org/resources/formapi.359/reviews]

Hey i have a problem i'll give them 5 stars too! How can I take the button now? Because this is not possible with me. (picture: https://ibb.co/2cy7WY0)

**Comment by ScarletRedMan** [comment]
Hi. What exactly do you want to take? Index of button? Button text?

**Comment by Bubbelwubbel** [comment]
hey, when you touch a button I want something to be done. because with pocketmine you have to do data and then case 0, but it doesn't work.

**Comment by ScarletRedMan** [comment]
I copied part of the code from the picture and this is working :/

**Comment by Bubbelwubbel** [comment]
Unfortunately not for me, what could be the reason?

**Comment by ScarletRedMan** [comment]
I don't know. But I advise using FormConstructor(better than FormAPI). And FormAPI is discontinued.
FormConstructor: https://github.com/ContentForge/FormConstructor

**Comment by Bubbelwubbel** [comment]
No, I'll stay with you <3. But I think I found the bug.
Thank you for your help.

**Comment by ScarletRedMan** [comment]
FormConstructor is my library with redesign code. It's fork of FormAPI :D

**Comment by Bubbelwubbel** [comment]
Oh, okay, then I'll use this now. Thanks very much!
